# Generated by Django 4.2.3 on 2023-11-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('basic', models.CharField(max_length=50, verbose_name='Бисквит')),
                ('cream', models.CharField(max_length=50, verbose_name='Крем')),
                ('filling', models.CharField(blank=True, max_length=50, null=True, verbose_name='Начинка')),
                ('compound', models.CharField(blank=True, max_length=250, null=True, verbose_name='Состав')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
                ('date', models.DateField()),
                ('img', models.ImageField(default='', upload_to='product_image/catalogs/classics')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.category')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Классические',
            },
        ),
    ]
