# Generated by Django 4.2.3 on 2023-11-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
    ]
